sua code

diff --git a/Infrastructure/CICD/Plan/Jenkinsfile b/Infrastructure/CICD/Plan/Jenkinsfile
--- a/Infrastructure/CICD/Plan/Jenkinsfile
+++ b/Infrastructure/CICD/Plan/Jenkinsfile
@@ -24,18 +24,23 @@ pipeline {
                 ]) {
                     script {
                         sh '''
-                        # Kiểm tra Terraform đã tồn tại chưa
-                        if ! command -v terraform &> /dev/null; then
-                            echo "Terraform not found. Downloading..."
-                            curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
-                            rm -f terraform # Xóa file cũ nếu có
-                            unzip -o terraform.zip # Giải nén và tự động ghi đè
-                            chmod +x terraform
-                            mv terraform /usr/local/bin/ || mv terraform ~/bin/
-                        else
-                            echo "Terraform already installed"
-                        fi
+                        sudo yum install -y yum-utils
+                        sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
+                        sudo yum -y install terraform
                     '''
+                    //     sh '''
+                    //     # Kiểm tra Terraform đã tồn tại chưa
+                    //     if ! command -v terraform &> /dev/null; then
+                    //         echo "Terraform not found. Downloading..."
+                    //         curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
+                    //         rm -f terraform # Xóa file cũ nếu có
+                    //         unzip -o terraform.zip # Giải nén và tự động ghi đè
+                    //         chmod +x terraform
+                    //         mv terraform /usr/local/bin/ || mv terraform ~/bin/
+                    //     else
+                    //         echo "Terraform already installed"
+                    //     fi
+                    // '''
                     }
                 }
             }
