sua code

diff --git a/Infrastructure/CICD/Plan/Jenkinsfile b/Infrastructure/CICD/Plan/Jenkinsfile
--- a/Infrastructure/CICD/Plan/Jenkinsfile
+++ b/Infrastructure/CICD/Plan/Jenkinsfile
@@ -24,22 +24,18 @@ pipeline {
                 ]) {
                     script {
                         sh '''
-                            # Kiểm tra Terraform đã cài hay chưa
-                            if ! command -v terraform &> /dev/null
-                            then
-                                echo "Terraform not found. Installing..."
-                                yum install -y yum-utils
-                                yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
-                                yum -y install terraform
+                            # Kiểm tra Terraform đã tồn tại chưa
+                            if ! command -v terraform &> /dev/null; then
+                                echo "Terraform not found. Downloading..."
+                                curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
+                                unzip terraform.zip
+                                chmod +x terraform
+                                sudo mv terraform /usr/local/bin/
                             else
                                 echo "Terraform already installed"
                             fi
-                            
-                            # Đảm bảo Terraform có quyền thực thi
-                            chmod +x ${TERRAFORM_BIN}
-                            
-                            # Kiểm tra lại phiên bản Terraform
-                            ${TERRAFORM_BIN} version
+
+                            terraform version
                         '''
                     }
                 }
