sua code

diff --git a/Infrastructure/CICD/Plan/Jenkinsfile b/Infrastructure/CICD/Plan/Jenkinsfile
--- a/Infrastructure/CICD/Plan/Jenkinsfile
+++ b/Infrastructure/CICD/Plan/Jenkinsfile
@@ -24,19 +24,17 @@ pipeline {
                 ]) {
                     script {
                         sh '''
-                            # Kiểm tra Terraform đã tồn tại chưa
-                            if ! command -v terraform &> /dev/null; then
-                                echo "Terraform not found. Downloading..."
-                                curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
-                                unzip terraform.zip
-                                chmod +x terraform
-                                sudo mv terraform /usr/local/bin/
-                            else
-                                echo "Terraform already installed"
-                            fi
-
-                            terraform version
-                        '''
+                        # Kiểm tra Terraform đã tồn tại chưa
+                        if ! command -v terraform &> /dev/null; then
+                            echo "Terraform not found. Downloading..."
+                            curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
+                            unzip terraform.zip
+                            chmod +x terraform
+                            mv terraform /usr/local/bin/ || mv terraform ~/bin/
+                        else
+                            echo "Terraform already installed"
+                        fi
+                    '''
                     }
                 }
             }
